# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(507, 605)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 60, 501, 551))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.settings_tab = QtGui.QWidget()
        self.settings_tab.setObjectName(_fromUtf8("settings_tab"))
        self.formLayoutWidget = QtGui.QWidget(self.settings_tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(130, 60, 231, 101))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_7 = QtGui.QLabel(self.formLayoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.SpanningRole, self.label_7)
        self.startFreq_box = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.startFreq_box.setMinimum(10.0)
        self.startFreq_box.setMaximum(19999.99)
        self.startFreq_box.setProperty("value", 1000.0)
        self.startFreq_box.setObjectName(_fromUtf8("startFreq_box"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.startFreq_box)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_2)
        self.stopFreq_box = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.stopFreq_box.setMinimum(10.0)
        self.stopFreq_box.setMaximum(20000.0)
        self.stopFreq_box.setProperty("value", 22.0)
        self.stopFreq_box.setObjectName(_fromUtf8("stopFreq_box"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.stopFreq_box)
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label)
        self.label_4 = QtGui.QLabel(self.settings_tab)
        self.label_4.setGeometry(QtCore.QRect(150, 10, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.settings_tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 470, 231, 51))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.checkBox_audioOutEnabled = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_audioOutEnabled.setObjectName(_fromUtf8("checkBox_audioOutEnabled"))
        self.verticalLayout.addWidget(self.checkBox_audioOutEnabled)
        self.tabWidget_3 = QtGui.QTabWidget(self.settings_tab)
        self.tabWidget_3.setGeometry(QtCore.QRect(30, 180, 451, 211))
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 381, 91))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.radio_contSweep = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.radio_contSweep.setChecked(True)
        self.radio_contSweep.setObjectName(_fromUtf8("radio_contSweep"))
        self.verticalLayout_2.addWidget(self.radio_contSweep)
        self.radio_discSweep = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.radio_discSweep.setObjectName(_fromUtf8("radio_discSweep"))
        self.verticalLayout_2.addWidget(self.radio_discSweep)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.scanTime_box = QtGui.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.scanTime_box.setMinimum(0.01)
        self.scanTime_box.setProperty("value", 3.0)
        self.scanTime_box.setObjectName(_fromUtf8("scanTime_box"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.scanTime_box)
        self.discScanSteps_box = QtGui.QSpinBox(self.horizontalLayoutWidget)
        self.discScanSteps_box.setMaximum(9999)
        self.discScanSteps_box.setProperty("value", 50)
        self.discScanSteps_box.setObjectName(_fromUtf8("discScanSteps_box"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.discScanSteps_box)
        self.label_9 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_9)
        self.horizontalLayout.addLayout(self.formLayout_3)
        self.tabWidget_3.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.tab_2)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(20, 10, 160, 91))
        self.verticalLayoutWidget_5.setObjectName(_fromUtf8("verticalLayoutWidget_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.radio_randomPhase = QtGui.QRadioButton(self.verticalLayoutWidget_5)
        self.radio_randomPhase.setChecked(True)
        self.radio_randomPhase.setObjectName(_fromUtf8("radio_randomPhase"))
        self.verticalLayout_3.addWidget(self.radio_randomPhase)
        self.radio_fixedPhase = QtGui.QRadioButton(self.verticalLayoutWidget_5)
        self.radio_fixedPhase.setObjectName(_fromUtf8("radio_fixedPhase"))
        self.verticalLayout_3.addWidget(self.radio_fixedPhase)
        self.formLayoutWidget_4 = QtGui.QWidget(self.tab_2)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(190, 10, 251, 161))
        self.formLayoutWidget_4.setObjectName(_fromUtf8("formLayoutWidget_4"))
        self.formLayout_4 = QtGui.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_8 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.combNumModes_box = QtGui.QSpinBox(self.formLayoutWidget_4)
        self.combNumModes_box.setMinimum(5)
        self.combNumModes_box.setMaximum(99999)
        self.combNumModes_box.setProperty("value", 500)
        self.combNumModes_box.setObjectName(_fromUtf8("combNumModes_box"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.combNumModes_box)
        self.combStatusBox = QtGui.QTextBrowser(self.formLayoutWidget_4)
        self.combStatusBox.setObjectName(_fromUtf8("combStatusBox"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.SpanningRole, self.combStatusBox)
        self.label_10 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_10)
        self.combNumCycles_box = QtGui.QSpinBox(self.formLayoutWidget_4)
        self.combNumCycles_box.setMinimum(1)
        self.combNumCycles_box.setMaximum(9999)
        self.combNumCycles_box.setProperty("value", 10)
        self.combNumCycles_box.setObjectName(_fromUtf8("combNumCycles_box"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.combNumCycles_box)
        self.tabWidget_3.addTab(self.tab_2, _fromUtf8(""))
        self.formLayoutWidget_5 = QtGui.QWidget(self.settings_tab)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(10, 420, 221, 41))
        self.formLayoutWidget_5.setObjectName(_fromUtf8("formLayoutWidget_5"))
        self.formLayout_5 = QtGui.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.gainSlider = QtGui.QSlider(self.formLayoutWidget_5)
        self.gainSlider.setMinimum(1)
        self.gainSlider.setMaximum(100)
        self.gainSlider.setProperty("value", 25)
        self.gainSlider.setOrientation(QtCore.Qt.Horizontal)
        self.gainSlider.setObjectName(_fromUtf8("gainSlider"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.gainSlider)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget_5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.tabWidget.addTab(self.settings_tab, _fromUtf8(""))
        self.plot_tab = QtGui.QWidget()
        self.plot_tab.setObjectName(_fromUtf8("plot_tab"))
        self.verticalLayoutWidget = QtGui.QWidget(self.plot_tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 481, 501))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.plot_layout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.plot_layout.setObjectName(_fromUtf8("plot_layout"))
        self.tabWidget.addTab(self.plot_tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.analysisMethod_box = QtGui.QComboBox(self.tab_3)
        self.analysisMethod_box.setGeometry(QtCore.QRect(20, 20, 171, 27))
        self.analysisMethod_box.setObjectName(_fromUtf8("analysisMethod_box"))
        self.analysisMethod_box.addItem(_fromUtf8(""))
        self.analysisMethod_box.addItem(_fromUtf8(""))
        self.tabWidget_2 = QtGui.QTabWidget(self.tab_3)
        self.tabWidget_2.setGeometry(QtCore.QRect(210, 20, 281, 121))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayoutWidget_6 = QtGui.QWidget(self.tab_5)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(20, 10, 131, 61))
        self.verticalLayoutWidget_6.setObjectName(_fromUtf8("verticalLayoutWidget_6"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.radioButton = QtGui.QRadioButton(self.verticalLayoutWidget_6)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.verticalLayout_4.addWidget(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.verticalLayoutWidget_6)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.verticalLayout_4.addWidget(self.radioButton_2)
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.tab_4)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 251, 81))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_6 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.numWavelets_box = QtGui.QSpinBox(self.formLayoutWidget_2)
        self.numWavelets_box.setMinimum(5)
        self.numWavelets_box.setMaximum(9999)
        self.numWavelets_box.setProperty("value", 50)
        self.numWavelets_box.setObjectName(_fromUtf8("numWavelets_box"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.numWavelets_box)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.formLayout_2.setItem(0, QtGui.QFormLayout.LabelRole, spacerItem)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.formLayout_2.setItem(2, QtGui.QFormLayout.LabelRole, spacerItem1)
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.analysisButton = QtGui.QPushButton(self.tab_3)
        self.analysisButton.setGeometry(QtCore.QRect(50, 60, 99, 27))
        self.analysisButton.setObjectName(_fromUtf8("analysisButton"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.tab_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(9, 139, 481, 371))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.fa_plotLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.fa_plotLayout.setObjectName(_fromUtf8("fa_plotLayout"))
        self.fa_progressBar = QtGui.QProgressBar(self.tab_3)
        self.fa_progressBar.setGeometry(QtCore.QRect(20, 100, 171, 23))
        self.fa_progressBar.setProperty("value", 0)
        self.fa_progressBar.setObjectName(_fromUtf8("fa_progressBar"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.scanButton = QtGui.QPushButton(Dialog)
        self.scanButton.setGeometry(QtCore.QRect(390, 20, 99, 27))
        self.scanButton.setObjectName(_fromUtf8("scanButton"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(160, 10, 221, 41))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.radio_sweepScan = QtGui.QRadioButton(self.horizontalLayoutWidget_2)
        self.radio_sweepScan.setChecked(True)
        self.radio_sweepScan.setObjectName(_fromUtf8("radio_sweepScan"))
        self.horizontalLayout_2.addWidget(self.radio_sweepScan)
        self.radio_combScan = QtGui.QRadioButton(self.horizontalLayoutWidget_2)
        self.radio_combScan.setObjectName(_fromUtf8("radio_combScan"))
        self.horizontalLayout_2.addWidget(self.radio_combScan)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label_7.setText(_translate("Dialog", "Scan Range", None))
        self.label_2.setText(_translate("Dialog", "Stop Freq (Hz)", None))
        self.label.setText(_translate("Dialog", "Start Freq (Hz)", None))
        self.label_4.setText(_translate("Dialog", "Scan Settings", None))
        self.checkBox_audioOutEnabled.setText(_translate("Dialog", "Audio Out Enabled", None))
        self.radio_contSweep.setText(_translate("Dialog", "Continuous", None))
        self.radio_discSweep.setText(_translate("Dialog", "Discrete", None))
        self.label_3.setText(_translate("Dialog", "Scan Time (sec)", None))
        self.label_9.setText(_translate("Dialog", "Discrete Steps", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab), _translate("Dialog", "Sweep", None))
        self.radio_randomPhase.setText(_translate("Dialog", "Random Phase", None))
        self.radio_fixedPhase.setText(_translate("Dialog", "Fixed Phase", None))
        self.label_8.setText(_translate("Dialog", "# Comb Modes", None))
        self.label_10.setText(_translate("Dialog", "# Cycles", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_2), _translate("Dialog", "Comb", None))
        self.label_5.setText(_translate("Dialog", "Gain", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings_tab), _translate("Dialog", "Settings", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.plot_tab), _translate("Dialog", "Plot", None))
        self.analysisMethod_box.setItemText(0, _translate("Dialog", "FFT", None))
        self.analysisMethod_box.setItemText(1, _translate("Dialog", "Wavelet", None))
        self.radioButton.setText(_translate("Dialog", "Amplitude", None))
        self.radioButton_2.setText(_translate("Dialog", "Phase", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("Dialog", "FFT", None))
        self.label_6.setText(_translate("Dialog", "# of Wavelets", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("Dialog", "Wavelet Options", None))
        self.analysisButton.setText(_translate("Dialog", "Analyze", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Freq Analysis", None))
        self.scanButton.setText(_translate("Dialog", "Scan", None))
        self.radio_sweepScan.setText(_translate("Dialog", "Sweep", None))
        self.radio_combScan.setText(_translate("Dialog", "Comb", None))

